### ISSUE TITLE
ingress controller tls example key issues

### ISSUE THREAD

**Issue by esbie** [linkerd/linkerd-examples#181]
Got a report that the tls part of the blog post no longer works
https://buoyant.io/2017/04/06/a-service-mesh-for-kubernetes-part-viii-linkerd-as-an-ingress-controller/

This may be due to the recent 1.2 upgrade where keys must now be in the pkcs8 format

**Comment by siggy** [comment]
confirmed TLS error:

```bash
curl --cacert k8s-daemonset/certificates/cert.pem -H "Host: world.v2" https://hello.world
```

yields:

```
WARN 0926 18:25:53.119 UTC finagle/netty4-8: Failed to initialize a channel. Closing: [id: 0xac585fd3, L:/10.16.2.45:443 - R:/199.116.73.216:63762]
java.lang.IllegalArgumentException: File does not contain valid private key: /io.buoyant/linkerd/certs/tls.key
	at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:267)
	at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:222)
	at io.netty.handler.ssl.SslContextBuilder.forServer(SslContextBuilder.java:54)
	at com.twitter.finagle.netty4.ssl.server.Netty4ServerEngineFactory.startWithKey(Netty4ServerEngineFactory.scala:23)
	at com.twitter.finagle.netty4.ssl.server.Netty4ServerEngineFactory.apply(Netty4ServerEngineFactory.scala:45)
	at com.twitter.finagle.netty4.ssl.server.Netty4ServerSslHandler.$anonfun$initChannel$1(Netty4ServerSslHandler.scala:75)
	at com.twitter.finagle.netty4.ssl.server.Netty4ServerSslHandler.$anonfun$initChannel$1$adapted(Netty4ServerSslHandler.scala:72)
	at scala.Option.foreach(Option.scala:257)
	at com.twitter.finagle.netty4.ssl.server.Netty4ServerSslHandler.initChannel(Netty4ServerSslHandler.scala:72)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
	at io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:178)
	at io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:143)
	at com.twitter.finagle.netty4.channel.Netty4RawServerChannelInitializer.initChannel(Netty4RawServerChannelInitializer.scala:54)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:226)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:392)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:379)
	at com.twitter.finagle.netty4.Netty4Listener$$anon$1$$anon$2.initChannel(Netty4Listener.scala:158)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
	at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44)
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1387)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1122)
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:647)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:506)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:419)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:478)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:24)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.security.spec.InvalidKeySpecException: Neither RSA, DSA nor EC worked
	at io.netty.handler.ssl.SslContext.getPrivateKeyFromByteBuffer(SslContext.java:1024)
	at io.netty.handler.ssl.SslContext.toPrivateKey(SslContext.java:993)
	at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:265)
	... 39 more
Caused by: java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: IOException : algid parse error, not a sequence
	at sun.security.ec.ECKeyFactory.engineGeneratePrivate(ECKeyFactory.java:169)
	at java.security.KeyFactory.generatePrivate(KeyFactory.java:372)
	at io.netty.handler.ssl.SslContext.getPrivateKeyFromByteBuffer(SslContext.java:1022)
	... 41 more
Caused by: java.security.InvalidKeyException: IOException : algid parse error, not a sequence
	at sun.security.pkcs.PKCS8Key.decode(PKCS8Key.java:351)
	at sun.security.pkcs.PKCS8Key.decode(PKCS8Key.java:356)
	at sun.security.ec.ECPrivateKeyImpl.<init>(ECPrivateKeyImpl.java:73)
	at sun.security.ec.ECKeyFactory.implGeneratePrivate(ECKeyFactory.java:237)
	at sun.security.ec.ECKeyFactory.engineGeneratePrivate(ECKeyFactory.java:165)
	... 43 more
```
